"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { IPC_AMBIGUITY_RULES, IPC_SEARCH_TAXONOMY } from "@/lib/ipc-nlp-taxonomy";

export type IpcHierarchyNode = { id:string; glosa:string; nivel:string; parentId:string|null; path:string[]; pathIds:string[] };
type Publication = { title:string; url:string; tags:string[] };
type Option = { kind:"node"; node:IpcHierarchyNode; source:"direct"|"synonym"; matchedBy?:string } | { kind:"publication"; publication:Publication; id:string };
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("es-CL").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const all=(haystack:string,terms:string[])=>terms.every(term=>haystack.includes(term));
const levelClass=(level:string)=>`ipc-level-${norm(level).replace(/[^a-z]/g,"")}`;

export default function IpcHierarchySelector({nodes,selectedIds,onAdd,onRemove,onNavigate,publications=[]}:{nodes:IpcHierarchyNode[];selectedIds:string[];onAdd:(id:string)=>void;onRemove:(id:string)=>void;onNavigate:(id:string)=>void;publications?:Publication[]}) {
  const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [activeIndex,setActiveIndex]=useState(0); const [openCrumb,setOpenCrumb]=useState<string|null>(null);
  const inputRef=useRef<HTMLInputElement>(null);
  const nodeById=useMemo(()=>new Map(nodes.map(node=>[node.id,node])),[nodes]);
  // La última serie elegida define las migas de navegación activas.
  const selectedId=selectedIds.at(-1)??"general";
  const selected=nodeById.get(selectedId)??nodes[0];
  const search=useMemo(()=>{
    const text=norm(query); if(text.length<2) return {direct:[] as Option[],synonyms:[] as Option[],publications:[] as Option[],ambiguity:""};
    const terms=text.split(" ").filter(Boolean); const preferred=new Set<string>();
    const rules=IPC_AMBIGUITY_RULES.filter(rule=>text.includes(norm(rule.term)));
    rules.forEach(rule=>rule.contexts.forEach(context=>{if(context.words.some(word=>text.includes(norm(word)))) preferred.add(context.preferId)}));
    const direct=nodes.filter(node=>node.id!=="general"&&!selectedIds.includes(node.id)).map(node=>{const label=norm(node.glosa),path=norm(node.path.join(" "));return{node,matches:all(label,terms)||all(path,terms),score:(preferred.has(node.id)?-10:0)+(label===text?0:label.startsWith(text)?1:label.includes(text)?2:3)}}).filter(item=>item.matches).sort((a,b)=>a.score-b.score||a.node.glosa.localeCompare(b.node.glosa,"es")).slice(0,12).map(({node})=>({kind:"node" as const,node,source:"direct" as const}));
    const directIds=new Set(direct.map(item=>item.node.id));
    const synonyms=IPC_SEARCH_TAXONOMY.map(entry=>{const lexical=[...entry.synonyms,...entry.tags].find(candidate=>all(norm(candidate),terms)||all(text,norm(candidate).split(" ")));const match=lexical||(preferred.has(entry.id)?"regla contextual":undefined);return{entry,node:nodeById.get(entry.id),match,score:(preferred.has(entry.id)?-10:0)+(match&&norm(match).startsWith(text)?0:1)}}).filter(item=>item.node&&item.match&&!directIds.has(item.entry.id)).sort((a,b)=>a.score-b.score||a.entry.official.localeCompare(b.entry.official,"es")).slice(0,12).map(({node,match})=>({kind:"node" as const,node:node!,source:"synonym" as const,matchedBy:match}));
    const related=publications.filter(publication=>publication.tags.some(tag=>all(norm(tag),terms)||text.includes(norm(tag)))).slice(0,4).map((publication,index)=>({kind:"publication" as const,publication,id:`publication-${index}`}));
    return{direct,synonyms,publications:related,ambiguity:rules.map(rule=>rule.description).join(" ")};
  },[nodeById,nodes,publications,query,selectedIds]);
  const options=[...search.direct,...search.synonyms,...search.publications];
  useEffect(()=>setActiveIndex(0),[query]);
  const closeSearch=()=>{setQuery("");setOpen(false);setOpenCrumb(null)};
  const addSeries=(id:string)=>{onAdd(id);closeSearch()};
  const navigate=(id:string)=>{onNavigate(id);closeSearch()};
  const activate=(option?:Option)=>{if(!option)return;if(option.kind==="node")addSeries(option.node.id);else window.open(option.publication.url,"_blank","noopener,noreferrer")};
  const onKeyDown=(event:React.KeyboardEvent<HTMLInputElement>)=>{if(event.key==="ArrowDown"){event.preventDefault();setOpen(true);setActiveIndex(index=>options.length?(index+1)%options.length:0)}else if(event.key==="ArrowUp"){event.preventDefault();setOpen(true);setActiveIndex(index=>options.length?(index-1+options.length)%options.length:0)}else if(event.key==="Enter"&&open&&options[activeIndex]){event.preventDefault();activate(options[activeIndex])}else if(event.key==="Escape"){setOpen(false);setQuery("")}};
  let cursor=-1;
  const renderGroup=(label:string,items:Option[],empty:string)=><section className="ipc-result-group" role="group" aria-label={label}><h3>{label}<span>{items.length}</span></h3>{items.length?items.map(option=>{cursor++;const index=cursor,active=index===activeIndex;if(option.kind==="publication")return <a key={option.id} id={`ipc-result-${option.id}`} role="option" aria-selected={active} className={`ipc-publication-result ${active?"is-active":""}`} href={option.publication.url} target="_blank" rel="noreferrer" onMouseDown={e=>e.preventDefault()} onMouseEnter={()=>setActiveIndex(index)}><span className="ipc-result-icon" aria-hidden="true">↗</span><span className="ipc-result-copy"><strong>{option.publication.title}</strong><small>Fuente oficial INE · abre en una pestaña nueva</small></span></a>;
    return <button type="button" id={`ipc-result-${option.node.id}-${option.source}`} role="option" aria-selected={active} className={active?"is-active":""} key={`${option.source}-${option.node.id}`} onMouseDown={e=>e.preventDefault()} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>addSeries(option.node.id)}><span className={`ipc-level-badge ${levelClass(option.node.nivel)}`}>{option.node.nivel}</span><span className="ipc-result-copy"><strong>{option.node.glosa}</strong><small>{option.source==="synonym"?`Sugerido por “${option.matchedBy}” · `:""}{option.node.path.slice(1,-1).join(" › ")}</small></span></button>}):<p>{empty}</p>}</section>;
  const active=options[activeIndex]; const activeId=active?.kind==="publication"?`ipc-result-${active.id}`:active?`ipc-result-${active.node.id}-${active.source}`:undefined;
  return <div className="ipc-hierarchy-navigation"><div className="ipc-omnibox"><div className="ipc-omnibox-field">{selectedIds.filter(id=>id!=="general").map(id=>{const node=nodeById.get(id);return node?<span className="ipc-active-chip" key={id}><span className={`ipc-level-badge ${levelClass(node.nivel)}`}>{node.nivel}</span><span>{node.glosa}</span><button type="button" aria-label={`Quitar ${node.glosa} del gráfico`} onClick={()=>onRemove(id)}>×</button></span>:null})}<input ref={inputRef} value={query} disabled={selectedIds.filter(id=>id!=="general").length>=5} onChange={e=>{setQuery(e.target.value);setOpen(e.target.value.trim().length>=2)}} onFocus={()=>query.trim().length>=2&&setOpen(true)} onBlur={()=>window.setTimeout(()=>setOpen(false),150)} onKeyDown={onKeyDown} role="combobox" aria-label="Buscar una serie del IPC por término oficial, sinónimo o expresión cotidiana" aria-expanded={open} aria-haspopup="listbox" aria-autocomplete="list" aria-controls="ipc-hierarchy-results" aria-activedescendant={open?activeId:undefined} placeholder={selectedIds.filter(id=>id!=="general").length>=5?"Máximo de 5 series alcanzado":"🔍 Agregar una serie (ej. Pan, Leche, Arriendo)…"}/></div>
  {open&&query.trim().length>=2&&<div id="ipc-hierarchy-results" className="ipc-search-results" role="listbox" aria-label="Coincidencias de la canasta IPC">{search.ambiguity&&<div className="ipc-ambiguity-note" role="note"><strong>Contexto aplicado</strong>{search.ambiguity}</div>}{renderGroup("Resultados directos · términos oficiales",search.direct,"Sin coincidencias oficiales.")}{renderGroup("Sugerencias por sinónimos y etiquetas",search.synonyms,"Sin sugerencias coloquiales.")}{renderGroup("Publicaciones y artículos relacionados",search.publications,"No hay publicaciones etiquetadas para esta búsqueda.")}</div>}</div>
  <nav className="ipc-breadcrumbs" aria-label="Ubicación de la última serie agregada">{selected.pathIds.map((id,index)=>{const node=nodeById.get(id)!;const children=nodes.filter(c=>c.parentId===id),siblings=id==="general"?[]:nodes.filter(c=>c.parentId===node.parentId),isLast=index===selected.pathIds.length-1,menuOptions=children.length?children:siblings;return <span className="ipc-crumb" key={id}>{index>0&&<span className="ipc-crumb-separator" aria-hidden="true">›</span>}<span className="ipc-crumb-menu"><span className="ipc-crumb-actions"><button type="button" className={isLast?"is-current":""} onClick={()=>navigate(id)}>{id==="general"?"IPC General":`${node.id} ${node.glosa}`}</button>{menuOptions.length>0&&<button type="button" className="ipc-crumb-toggle" aria-label={`Mostrar alternativas para ${node.glosa}`} aria-expanded={openCrumb===id} onClick={()=>setOpenCrumb(openCrumb===id?null:id)}>▾</button>}</span>{openCrumb===id&&menuOptions.length>0&&<div className="ipc-sibling-menu" role="menu" onKeyDown={event=>{const buttons=Array.from(event.currentTarget.querySelectorAll("button"));const current=buttons.indexOf(document.activeElement as HTMLButtonElement);if(event.key==="Escape"){setOpenCrumb(null);inputRef.current?.focus()}if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();const step=event.key==="ArrowDown"?1:-1;buttons[(current+step+buttons.length)%buttons.length]?.focus()}}}>{menuOptions.map(option=><button type="button" role="menuitem" key={option.id} onClick={()=>navigate(option.id)}>{option.id} {option.glosa}</button>)}</div>}</span></span>})}</nav></div>;
}
