import * as XLSX from "xlsx";

type Point={year:number;month:number;label:string;value:number;monthly:number|null;annual:number|null;accumulated:number|null};
const months:Record<string,number>={ene:1,feb:2,mar:3,abr:4,may:5,jun:6,jul:7,ago:8,sept:9,sep:9,oct:10,nov:11,dic:12};
const clean=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:null;
function period(value:unknown){const match=String(value??"").trim().toLowerCase().match(/^([a-záéíóú]+)-(\d{2})$/);if(!match)return null;const month=months[match[1]];return month?{month,year:2000+Number(match[2]),label:String(value)}:null;}
function calc(points:{year:number;month:number;label:string;value:number}[]):Point[]{return points.map((point,index)=>{const previous=points[index-1],yearAgo=points.find(item=>item.year===point.year-1&&item.month===point.month);const currentYtd=points.filter(item=>item.year===point.year&&item.month<=point.month).reduce((sum,item)=>sum+item.value,0);const priorYtd=points.filter(item=>item.year===point.year-1&&item.month<=point.month);const priorTotal=priorYtd.reduce((sum,item)=>sum+item.value,0);return {...point,monthly:previous?(point.value/previous.value-1)*100:null,annual:yearAgo?(point.value/yearAgo.value-1)*100:null,accumulated:priorYtd.length===point.month&&priorTotal?(currentYtd/priorTotal-1)*100:null};});}
function parseIndex(sheet:XLSX.WorkSheet){const rows=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:null});return rows.slice(6).flatMap(row=>{const p=period(row[1]);if(!p||clean(row[2])===null)return[];return [{...p,current:{value:clean(row[2]),monthly:clean(row[3]),annual:clean(row[4]),accumulated:clean(row[5])},constant:{value:clean(row[6]),monthly:clean(row[7]),annual:clean(row[8]),accumulated:clean(row[9])}}];});}
function parseMatrix(sheet:XLSX.WorkSheet){const rows=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,raw:true,defval:null}),headers=rows[5];const territories=headers.slice(2,19).map(value=>String(value));const raw=Object.fromEntries(territories.map((territory,column)=>[territory,rows.slice(6).flatMap(row=>{const p=period(row[1]),value=clean(row[column+2]);return p&&value!==null?[{...p,value}]:[]})]));return {territories,seriesByTerritory:Object.fromEntries(Object.entries(raw).map(([key,value])=>[key,calc(value)]))};}

export function parseSupermarketsWorkbook(buffer:ArrayBuffer){const book=XLSX.read(buffer,{type:"array"});const regionalSheets=["3.15","3.1","3.2","3.3","3.4","3.5","3.13","3.6","3.7","3.16","3.8","3.9","3.14","3.10","3.11","3.12"];
  const indexByTerritory:Record<string,ReturnType<typeof parseIndex>>={Nacional:parseIndex(book.Sheets["1"])};
  for(const sheet of regionalSheets){const title=String(book.Sheets[sheet]?.A3?.v??"");const name=(title.match(/REGIÓN (?:DE |DEL )?(.+?)(?:\/|$)/i)?.[1]??sheet).replace("METROPOLITANA","Metropolitana").toLowerCase().replace(/(^|\s|')\p{L}/gu,letter=>letter.toUpperCase());indexByTerritory[name]=parseIndex(book.Sheets[sheet]);}
  return {kind:"supermarkets",base:"Base promedio año 2018=100",territories:Object.keys(indexByTerritory),indexByTerritory,matrices:{sales:parseMatrix(book.Sheets["4"]),stores:parseMatrix(book.Sheets["5"]),area:parseMatrix(book.Sheets["6"])}};
}
