import {NextRequest,NextResponse} from "next/server";
import {parseSupermarketsWorkbook} from "../../../lib/supermarkets-data";
import {sha256} from "../../../lib/source-hash";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const sourceUrl="https://www.ine.gob.cl/docs/default-source/ventas-de-supermercados/cuadros-estadisticos/base-promedio-a%C3%B1o-2018-100/series-mensuales-desde-enero-de-2018-a-la-fecha.xls";
type D1Database={prepare:(sql:string)=>{bind:(...values:unknown[])=>any;run:()=>Promise<any>;first:<T>()=>Promise<T|null>;all:<T>()=>Promise<{results:T[]}>}};
type Meta={etag:string;last_modified:string;size:string;cache_key:string;checked_at:string;updated_at:string};
async function load(db:D1Database,key:string){const result=await db.prepare("SELECT part,payload FROM supermarkets_payload_v1 WHERE cache_key=? ORDER BY part").bind(key).all<{part:string;payload:string}>();if(result.results.length<21)return null;const rows=Object.fromEntries(result.results.map(row=>[row.part,JSON.parse(row.payload)])),indexByTerritory=Object.fromEntries(Object.entries(rows).filter(([part])=>part.startsWith("index:")).map(([part,value])=>[part.slice(6),value])),matrices=Object.fromEntries(Object.entries(rows).filter(([part])=>part.startsWith("matrix:")).map(([part,value])=>[part.slice(7),value]));return {...rows.meta,indexByTerritory,matrices};}
export async function GET(request:NextRequest){try{const db=(globalThis as typeof globalThis&{__SITES_DB?:D1Database}).__SITES_DB;if(!db)throw new Error("La caché compartida no está disponible");await db.prepare("CREATE TABLE IF NOT EXISTS supermarkets_meta_v1 (id TEXT PRIMARY KEY, etag TEXT, last_modified TEXT, size TEXT, cache_key TEXT, checked_at TEXT, updated_at TEXT)").run();await db.prepare("CREATE TABLE IF NOT EXISTS supermarkets_payload_v1 (cache_key TEXT, part TEXT, payload TEXT, PRIMARY KEY(cache_key,part))").run();const cached=await db.prepare("SELECT * FROM supermarkets_meta_v1 WHERE id='supermarkets'").first<Meta>();const refresh=request.nextUrl.searchParams.get("refresh")==="1";if(cached&&!refresh){const payload=await load(db,cached.cache_key);if(payload)return NextResponse.json({...payload,source:{url:sourceUrl,cache:"cached",checkedAt:cached.checked_at}},{headers:{"Cache-Control":"no-store","Server-Timing":"data;desc=shared-cache"}});}const now=new Date().toISOString();const response=await fetch(sourceUrl,{cache:"no-store"});if(!response.ok)throw new Error(`Fuente INE: ${response.status}`);const bytes=await response.arrayBuffer(),hash=await sha256(bytes);if(cached&&cached.etag===hash){const payload=await load(db,cached.cache_key);if(payload){await db.prepare("UPDATE supermarkets_meta_v1 SET checked_at=? WHERE id='supermarkets'").bind(now).run();return NextResponse.json({...payload,source:{url:sourceUrl,cache:"shared",checkedAt:now}});}}const payload=parseSupermarketsWorkbook(bytes),key=now.replace(/\D/g,"");const parts:Record<string,unknown>={meta:{kind:payload.kind,base:payload.base,territories:payload.territories}};for(const [name,value] of Object.entries(payload.indexByTerritory))parts[`index:${name}`]=value;for(const [name,value] of Object.entries(payload.matrices))parts[`matrix:${name}`]=value;for(const [part,value] of Object.entries(parts))await db.prepare("INSERT INTO supermarkets_payload_v1(cache_key,part,payload) VALUES(?,?,?)").bind(key,part,JSON.stringify(value)).run();await db.prepare("INSERT INTO supermarkets_meta_v1 VALUES('supermarkets',?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET etag=excluded.etag,last_modified=excluded.last_modified,size=excluded.size,cache_key=excluded.cache_key,checked_at=excluded.checked_at,updated_at=excluded.updated_at").bind(hash,null,null,key,now,now).run();await db.prepare("DELETE FROM supermarkets_payload_v1 WHERE cache_key<>?").bind(key).run();return NextResponse.json({...payload,source:{url:sourceUrl,cache:"updated",checkedAt:now}});
}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"No fue posible cargar las series"},{status:500});}}
